/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as IEX from "./src/types/iexCloud"
import * as PrismaClient from "./../node_modules/.prisma/client/index"
import { Context } from "./src/context"
import { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>
    crud: any
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  WatchlistWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AlphaVantageSymbol: { // root type
    currency?: string | null; // String
    marketClose?: string | null; // String
    marketOpen?: string | null; // String
    name?: string | null; // String
    region?: string | null; // String
    symbol?: string | null; // String
    timezone?: string | null; // String
    type?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Share: PrismaClient.Share;
  ShareQuote: IEX.ShareQuote;
  User: PrismaClient.User;
  Watchlist: PrismaClient.Watchlist;
  WatchlistShares: PrismaClient.WatchlistShares;
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AlphaVantageSymbol: { // field return type
    currency: string | null; // String
    marketClose: string | null; // String
    marketOpen: string | null; // String
    name: string | null; // String
    region: string | null; // String
    symbol: string | null; // String
    timezone: string | null; // String
    type: string | null; // String
  }
  Mutation: { // field return type
    addShareToWatchlist: NexusGenRootTypes['WatchlistShares']; // WatchlistShares!
    createWatchlist: NexusGenRootTypes['Watchlist']; // Watchlist!
    removeShareFromWatchList: NexusGenRootTypes['WatchlistShares']; // WatchlistShares!
  }
  Query: { // field return type
    symbolSearch: Array<NexusGenRootTypes['AlphaVantageSymbol'] | null> | null; // [AlphaVantageSymbol]
    watchlist: NexusGenRootTypes['Watchlist'] | null; // Watchlist
    watchlists: Array<NexusGenRootTypes['Watchlist'] | null> | null; // [Watchlist]
  }
  Share: { // field return type
    companyName: string; // String!
    country: string | null; // String
    description: string; // String!
    exchange: string; // String!
    id: number; // Int!
    industry: string; // String!
    issueType: string; // String!
    sector: string; // String!
    symbol: string; // String!
  }
  ShareQuote: { // field return type
    addedAt: NexusGenScalars['DateTime'] | null; // DateTime
    addedPrice: number | null; // Float
    change: number | null; // Float
    changePercent: number | null; // Float
    changePercentSinceAdded: number | null; // Float
    changeSinceAdded: number | null; // Float
    companyName: string | null; // String
    high: number | null; // Float
    latestPrice: number | null; // Float
    latestUpdate: number | null; // Float
    latestVolume: number | null; // Float
    low: number | null; // Float
    open: number | null; // Float
    shareId: number | null; // Int
    symbol: string | null; // String
  }
  User: { // field return type
    email: string | null; // String
    familyName: string | null; // String
    givenName: string | null; // String
    id: number; // Int!
    picture: string | null; // String
    sub: string; // String!
    watchlists: NexusGenRootTypes['Watchlist'][]; // [Watchlist!]!
  }
  Watchlist: { // field return type
    id: number; // Int!
    name: string; // String!
    shares: Array<NexusGenRootTypes['ShareQuote'] | null> | null; // [ShareQuote]
    user: NexusGenRootTypes['User']; // User!
  }
  WatchlistShares: { // field return type
    price: number; // Float!
  }
}

export interface NexusGenFieldTypeNames {
  AlphaVantageSymbol: { // field return type name
    currency: 'String'
    marketClose: 'String'
    marketOpen: 'String'
    name: 'String'
    region: 'String'
    symbol: 'String'
    timezone: 'String'
    type: 'String'
  }
  Mutation: { // field return type name
    addShareToWatchlist: 'WatchlistShares'
    createWatchlist: 'Watchlist'
    removeShareFromWatchList: 'WatchlistShares'
  }
  Query: { // field return type name
    symbolSearch: 'AlphaVantageSymbol'
    watchlist: 'Watchlist'
    watchlists: 'Watchlist'
  }
  Share: { // field return type name
    companyName: 'String'
    country: 'String'
    description: 'String'
    exchange: 'String'
    id: 'Int'
    industry: 'String'
    issueType: 'String'
    sector: 'String'
    symbol: 'String'
  }
  ShareQuote: { // field return type name
    addedAt: 'DateTime'
    addedPrice: 'Float'
    change: 'Float'
    changePercent: 'Float'
    changePercentSinceAdded: 'Float'
    changeSinceAdded: 'Float'
    companyName: 'String'
    high: 'Float'
    latestPrice: 'Float'
    latestUpdate: 'Float'
    latestVolume: 'Float'
    low: 'Float'
    open: 'Float'
    shareId: 'Int'
    symbol: 'String'
  }
  User: { // field return type name
    email: 'String'
    familyName: 'String'
    givenName: 'String'
    id: 'Int'
    picture: 'String'
    sub: 'String'
    watchlists: 'Watchlist'
  }
  Watchlist: { // field return type name
    id: 'Int'
    name: 'String'
    shares: 'ShareQuote'
    user: 'User'
  }
  WatchlistShares: { // field return type name
    price: 'Float'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addShareToWatchlist: { // args
      symbol: string; // String!
      watchlistId: string; // ID!
    }
    createWatchlist: { // args
      name: string; // String!
    }
    removeShareFromWatchList: { // args
      shareId: number; // Int!
      watchlistId: number; // Int!
    }
  }
  Query: {
    symbolSearch: { // args
      symbol: string; // String!
    }
    watchlist: { // args
      id: string; // ID!
    }
  }
  User: {
    watchlists: { // args
      after?: NexusGenInputs['WatchlistWhereUniqueInput'] | null; // WatchlistWhereUniqueInput
      before?: NexusGenInputs['WatchlistWhereUniqueInput'] | null; // WatchlistWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}